package validator

import "sort"

// ImplementationStatus indicates how fully an S/F pair is implemented.
type ImplementationStatus int

const (
	ImplFull    ImplementationStatus = iota // Fully implemented
	ImplPartial                            // Partially implemented
	ImplNone                               // Not implemented
)

func (s ImplementationStatus) String() string {
	switch s {
	case ImplFull:
		return "FULL"
	case ImplPartial:
		return "PARTIAL"
	case ImplNone:
		return "NONE"
	default:
		return "?"
	}
}

// SFCoverage describes a single S/F pair's implementation status.
type SFCoverage struct {
	Stream    byte                 `json:"stream"`
	Function  byte                 `json:"function"`
	Name      string               `json:"name"`
	Direction string               `json:"direction"`
	Standard  string               `json:"standard"`
	Status    ImplementationStatus `json:"status"`
}

// StandardCoverage summarizes coverage for one SEMI standard.
type StandardCoverage struct {
	Standard   string  `json:"standard"`
	Handled    int     `json:"handled"`
	Expected   int     `json:"expected"`
	Percentage float64 `json:"percentage"`
}

// CoverageReport describes the overall implementation coverage.
type CoverageReport struct {
	Standards    []StandardCoverage `json:"standards"`
	SFDetail     []SFCoverage       `json:"sfDetail"`
	TotalHandled int                `json:"totalHandled"`
	TotalExpected int               `json:"totalExpected"`
	Percentage   float64            `json:"percentage"`
}

// handledSFs lists the S/F pairs that the built-in GEM handler processes.
// This is derived from the switch statement in handler.go HandleMessage().
var handledSFs = map[sfKey]bool{
	// Requests handled by equipment (built-in)
	{1, 1}: true, {1, 3}: true, {1, 11}: true, {1, 13}: true,
	{1, 15}: true, {1, 17}: true,
	{2, 13}: true, {2, 15}: true, {2, 29}: true,
	{2, 33}: true, {2, 35}: true, {2, 37}: true, {2, 41}: true,
	{5, 3}: true, {5, 5}: true, {5, 7}: true,
	// Replies generated by equipment (built-in)
	{1, 2}: true, {1, 4}: true, {1, 12}: true, {1, 14}: true,
	{1, 16}: true, {1, 18}: true,
	{2, 14}: true, {2, 16}: true, {2, 30}: true,
	{2, 34}: true, {2, 36}: true, {2, 38}: true, {2, 42}: true,
	{5, 4}: true, {5, 6}: true, {5, 8}: true,
	// Equipment-initiated (SendAlarm, SendEvent)
	{5, 1}: true, {6, 11}: true,
}

// GenerateReport produces a coverage report by comparing the schema registry
// against the known set of handled S/F pairs.
func GenerateReport(registry *SchemaRegistry) *CoverageReport {
	schemas := registry.All()

	// Sort by stream, then function
	sort.Slice(schemas, func(i, j int) bool {
		if schemas[i].Stream != schemas[j].Stream {
			return schemas[i].Stream < schemas[j].Stream
		}
		return schemas[i].Function < schemas[j].Function
	})

	report := &CoverageReport{}
	stdMap := make(map[string]*StandardCoverage)

	for _, s := range schemas {
		key := sfKey{s.Stream, s.Function}
		status := ImplNone
		if handledSFs[key] {
			status = ImplFull
		}

		report.SFDetail = append(report.SFDetail, SFCoverage{
			Stream:    s.Stream,
			Function:  s.Function,
			Name:      s.Name,
			Direction: s.Direction.String(),
			Standard:  s.Standard,
			Status:    status,
		})

		// Aggregate by standard
		sc, ok := stdMap[s.Standard]
		if !ok {
			sc = &StandardCoverage{Standard: s.Standard}
			stdMap[s.Standard] = sc
		}
		sc.Expected++
		if status == ImplFull || status == ImplPartial {
			sc.Handled++
		}
	}

	// Build standard summaries
	for _, sc := range stdMap {
		if sc.Expected > 0 {
			sc.Percentage = float64(sc.Handled) / float64(sc.Expected) * 100
		}
		report.Standards = append(report.Standards, *sc)
		report.TotalHandled += sc.Handled
		report.TotalExpected += sc.Expected
	}
	sort.Slice(report.Standards, func(i, j int) bool {
		return report.Standards[i].Standard < report.Standards[j].Standard
	})

	if report.TotalExpected > 0 {
		report.Percentage = float64(report.TotalHandled) / float64(report.TotalExpected) * 100
	}

	return report
}
